
#define INVENTORY_NONE				0
//armor
#define INVENTORY_ARMOR				1
//weapons
#define INVENTORY_GAUNTLET			4
#define INVENTORY_SHOTGUN			5
#define INVENTORY_MACHINEGUN		6
#define INVENTORY_GRENADELAUNCHER	7
#define INVENTORY_ROCKETLAUNCHER	8
#define INVENTORY_LIGHTNING			9
#define INVENTORY_RAILGUN			10
#define INVENTORY_PLASMAGUN			11
#define INVENTORY_BFG10K			13
#define INVENTORY_GRAPPLINGHOOK		14
#define INVENTORY_NAILGUN			15
#define INVENTORY_PROXLAUNCHER		16
#define INVENTORY_CHAINGUN			17
#define INVENTORY_HMG				18
//ammo
#define INVENTORY_SHELLS			19
#define INVENTORY_BULLETS			20
#define INVENTORY_GRENADES			21
#define INVENTORY_CELLS				22
#define INVENTORY_LIGHTNINGAMMO		23
#define INVENTORY_ROCKETS			24
#define INVENTORY_SLUGS				25
#define INVENTORY_BFGAMMO			26
#define INVENTORY_NAILS				27
#define INVENTORY_MINES				28
#define INVENTORY_BELT				29
#define INVENTORY_HBULLETS			30
#define INVENTORY_AMMOPACK			31
//powerups
#define INVENTORY_HEALTH			32
#define INVENTORY_TELEPORTER		33
#define INVENTORY_MEDKIT			34
#define INVENTORY_KAMIKAZE			35
#define INVENTORY_PORTAL			36
#define INVENTORY_INVULNERABILITY	37
#define INVENTORY_KEY_SILVER		38
#define INVENTORY_KEY_GOLD			39
#define INVENTORY_KEY_MASTER		40
#define INVENTORY_FLIGHT			41

#define INVENTORY_QUAD				42
#define INVENTORY_ENVIRONMENTSUIT	43
#define INVENTORY_HASTE				44
#define INVENTORY_INVISIBILITY		45
#define INVENTORY_REGEN				46
#define INVENTORY_SCOUT				47
#define INVENTORY_GUARD				48
#define INVENTORY_DAMAGE			49
#define INVENTORY_ARMORREGEN		50

#define INVENTORY_REDFLAG			51
#define INVENTORY_BLUEFLAG			52
#define INVENTORY_NEUTRALFLAG		53
#define INVENTORY_RED_SKULL			54
#define INVENTORY_BLUE_SKULL		55
//enemy stuff
#define ENEMY_HORIZONTAL_DIST		200
#define ENEMY_HEIGHT				201
#define NUM_VISIBLE_ENEMIES			202
#define NUM_VISIBLE_TEAMMATES		203

//item numbers (make sure they are in sync with bg_itemlist in bg_misc.c)
#define MODELINDEX_ARMORSHARD		1
#define MODELINDEX_ARMOR_YELLOW		2
#define MODELINDEX_ARMOR_RED		3
#define MODELINDEX_ARMOR_GREEN		4
#define MODELINDEX_HEALTHSMALL		4
#define MODELINDEX_HEALTH			5
#define MODELINDEX_HEALTHLARGE		6
#define MODELINDEX_HEALTHMEGA		7

#define MODELINDEX_GAUNTLET			8
#define MODELINDEX_SHOTGUN			9
#define MODELINDEX_MACHINEGUN		10
#define MODELINDEX_GRENADELAUNCHER	11
#define MODELINDEX_ROCKETLAUNCHER	12
#define MODELINDEX_LIGHTNING		13
#define MODELINDEX_RAILGUN			14
#define MODELINDEX_PLASMAGUN		15
#define MODELINDEX_BFG10K			16
#define MODELINDEX_GRAPPLINGHOOK	17

#define MODELINDEX_SHELLS			18
#define MODELINDEX_BULLETS			19
#define MODELINDEX_GRENADES			20
#define MODELINDEX_CELLS			21
#define MODELINDEX_LIGHTNINGAMMO	22
#define MODELINDEX_ROCKETS			23
#define MODELINDEX_SLUGS			24
#define MODELINDEX_BFGAMMO			25

#define MODELINDEX_TELEPORTER		26
#define MODELINDEX_MEDKIT			27
#define MODELINDEX_QUAD				28
#define MODELINDEX_ENVIRONMENTSUIT	29
#define MODELINDEX_HASTE			30
#define MODELINDEX_INVISIBILITY		31
#define MODELINDEX_REGEN			32
#define MODELINDEX_FLIGHT			33

#define MODELINDEX_REDFLAG			34
#define MODELINDEX_BLUEFLAG			35

#define MODELINDEX_KAMIKAZE			36
#define MODELINDEX_PORTAL			37
#define MODELINDEX_INVULNERABILITY	38

#define MODELINDEX_NAILS			39
#define MODELINDEX_MINES			40
#define MODELINDEX_BELT				41

#define MODELINDEX_SCOUT			42
#define MODELINDEX_GUARD			43
#define MODELINDEX_DAMAGE			44
#define MODELINDEX_ARMORREGEN		45

#define MODELINDEX_NEUTRALFLAG		46
#define MODELINDEX_RED_SKULL		47
#define MODELINDEX_BLUE_SKULL		48

#define MODELINDEX_NAILGUN			49
#define MODELINDEX_PROXLAUNCHER		50
#define MODELINDEX_CHAINGUN			51

#define MODELINDEX_SPAWN_ARMOR		52

#define MODELINDEX_HMG				53
#define MODELINDEX_HBULLETS			54
#define MODELINDEX_AMMO_PACK		55

#define MODELINDEX_KEY_SILVER		56
#define MODELINDEX_KEY_GOLD			57
#define MODELINDEX_KEY_MASTER		58

//
#define WEAPONINDEX_GAUNTLET			1
#define WEAPONINDEX_MACHINEGUN			2
#define WEAPONINDEX_SHOTGUN				3
#define WEAPONINDEX_GRENADE_LAUNCHER	4
#define WEAPONINDEX_ROCKET_LAUNCHER		5
#define WEAPONINDEX_LIGHTNING			6
#define WEAPONINDEX_RAILGUN				7
#define WEAPONINDEX_PLASMAGUN			8
#define WEAPONINDEX_BFG					9
#define WEAPONINDEX_GRAPPLING_HOOK		10
#define WEAPONINDEX_NAILGUN				11
#define WEAPONINDEX_PROXLAUNCHER		12
#define WEAPONINDEX_CHAINGUN			13
#define WEAPONINDEX_HMG					14
